services:
  frontend:
    container_name: 'next-js'
    build: src/main/frontend
    depends_on:
      - backend
    networks:
      - retro-net
    ports:
      - "3000:3000"

  backend:
    container_name: 'spring-mvc'
    build:
      context: .
      dockerfile: src/main/java/Dockerfile
    networks:
      - retro-net
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    container_name: 'maria-db'
    image: mariadb:latest
    restart: always
    networks:
      - retro-net
    environment:
      MARIADB_ROOT_PASSWORD: root_pwd
      MARIADB_DATABASE: retro_store
      MARIADB_USER: tarell
      MARIADB_PASSWORD: my_pwd
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d

  nginx:
    image: nginx:alpine
    container_name: 'nginx'
    restart: unless-stopped
    networks:
      - retro-net
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

volumes:
  mariadb_data: { }

networks:
  retro-net:
    driver: bridge
