services:
  frontend:
    container_name: 'next-js'
    build:
      context: .
      dockerfile: ./src/main/js/Dockerfile
    depends_on:
      - backend
    ports:
      - "3000:3000"
    restart: always

  backend:
    container_name: 'spring-mvc'
    build:
      context: .
      dockerfile: ./src/main/java/Dockerfile
    ports:
      - "8080:8080"
    restart: always

  nginx:
    image: nginx:alpine
    container_name: 'nginx'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - backend
      - frontend



