services:
  frontend:
    container_name: 'next-js'
    build: src/main/frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"

  backend:
    container_name: 'spring-mvc'
    build:
      context: .
      dockerfile: src/main/java/Dockerfile
    ports:
      - "8080:8080"

  nginx:
    image: nginx:alpine
    container_name: 'nginx'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend



