version: "0.0.1"
services:
  frontend:
    build:
      context: .
      dockerfile: ./src/main/js/Dockerfile
    ports:
      - "3000:3000"
    networks:
      - front-tier
      - back-tier
  backend:
    build:
      context: .
      dockerfile: ./src/main/java/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - front-tier
      - back-tier
networks:
  front-tier: { }
  back-tier: { }
